

services:
  mysql:
    image: mysql:8
    container_name: manga-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mangadb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  manga-service:
    build: .
    container_name: manga-service
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/mangadb
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  mysql-data:
