

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mangas
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  manga-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@database:3306/mangas
      JWT_SECRET: supersecret
      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret
    depends_on:
      - database

volumes:
  db-data:
